#!/usr/bin/env python3
"""Skill overlay parsing and marker-block transformations."""

from __future__ import annotations

import difflib
import re
from pathlib import Path

from marshmallow_workspace import MarshmallowError, timestamp
from safety import validate_generated_guidance

REQUIRED_OVERLAY_HEADINGS = {
    "## Marshmallow Alignment",
    "### Preserve",
    "### Override Defaults",
    "### Quality Bar",
    "### Anti-Patterns",
    "### Ask When",
    "### Source Trail",
}
START_MARKER = "<!-- marshmallow:alignment:start -->"
END_MARKER = "<!-- marshmallow:alignment:end -->"
ID_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def validate_overlay(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    missing = [heading for heading in sorted(REQUIRED_OVERLAY_HEADINGS) if heading not in text]
    if missing:
        raise MarshmallowError(f"{path}: missing overlay headings: {', '.join(missing)}")
    validate_generated_guidance(text, path, max_chars=4000)


def normalize_skill_file(path: Path) -> Path:
    path = path.expanduser()
    normalized = path / "SKILL.md" if path.is_dir() else path
    if normalized.name != "SKILL.md":
        raise MarshmallowError(f"Skill target must be a SKILL.md file: {normalized}")
    return normalized


def is_writable(path: Path) -> bool:
    return bool(path.stat().st_mode & 0o222)


def skill_id(path: Path) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "-", path.parent.name.lower()).strip("-")
    if not normalized:
        raise MarshmallowError(f"Could not derive skill id from {path}")
    return normalized


def backup_path(root: Path, target: Path) -> Path:
    base = root / "backups" / timestamp() / skill_id(target) / "SKILL.md"
    if not base.exists():
        return base
    counter = 2
    while True:
        candidate = base.parent.parent / f"{base.parent.name}-{counter}" / "SKILL.md"
        if not candidate.exists():
            return candidate
        counter += 1


def ensure_generated_skill_name(text: str, generated_name: str) -> str:
    if not ID_PATTERN.match(generated_name):
        raise MarshmallowError(f"Generated skill directory must use lowercase hyphen-case: {generated_name!r}")
    if not text.startswith("---\n"):
        return f"---\nname: {generated_name}\ndescription: Personalized skill generated by Marshmallow.\n---\n\n{text}"
    closing = text.find("\n---\n", 4)
    if closing == -1:
        raise MarshmallowError("Generated aligned copy has unclosed frontmatter")
    frontmatter = text[4:closing]
    if re.search(r"^name:\s*", frontmatter, flags=re.MULTILINE):
        frontmatter = re.sub(r"^name:\s*.*$", f"name: {generated_name}", frontmatter, flags=re.MULTILINE)
    else:
        frontmatter = f"name: {generated_name}\n{frontmatter}"
    return f"---\n{frontmatter}\n---\n{text[closing + 5:]}"


def alignment_block(overlay_path: Path) -> str:
    return (
        f"{START_MARKER}\n"
        "## Marshmallow Alignment\n\n"
        f"Before using this skill, read `{overlay_path.resolve()}` and apply it as the personal alignment layer.\n"
        f"{END_MARKER}"
    )


def apply_marker(original: str, overlay_path: Path) -> str:
    block = alignment_block(overlay_path)
    if START_MARKER not in original and END_MARKER not in original:
        return original.rstrip() + "\n\n" + block + "\n"
    if original.count(START_MARKER) != 1 or original.count(END_MARKER) != 1:
        raise MarshmallowError("Skill contains malformed or duplicate Marshmallow marker blocks")
    start = original.index(START_MARKER)
    end = original.index(END_MARKER) + len(END_MARKER)
    return original[:start].rstrip() + "\n\n" + block + original[end:].rstrip() + "\n"


def unified_diff(target: Path, original: str, updated: str) -> str:
    return "".join(
        difflib.unified_diff(
            original.splitlines(keepends=True),
            updated.splitlines(keepends=True),
            fromfile=str(target),
            tofile=str(target),
        )
    )
